#!/usr/bin/env bash
#
# stage-content.sh — move generated artifacts to the outbox for founder review
#
# Usage:
#   bash ~/.claude/skills/empire-builder/scripts/stage-content.sh <slug> <type> [source]
#
# Types:
#   phase <N>      — stage all artifacts from GSD phase N's SUMMARY.md
#   content        — stage this week's content pieces to outbox/content-pieces/YYYY-MM-DD/
#   loop           — stage today's growth loop increment to outbox/YYYY-MM-DD/
#
# Examples:
#   bash stage-content.sh manifest-and-thrive phase 1
#   bash stage-content.sh manifest-and-thrive content
#   bash stage-content.sh manifest-and-thrive loop
#
set -uo pipefail

SKILL_DIR="${HOME}/.claude/skills/empire-builder"
CLIENTS_DIR="${SKILL_DIR}/clients"
TEMPLATES_DIR="${SKILL_DIR}/templates"

bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
ok()    { printf '  \033[0;32m✓\033[0m %s\n' "$*"; }
warn()  { printf '  \033[0;33m!\033[0m %s\n' "$*"; }
step()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

if [ -z "${1:-}" ] || [ -z "${2:-}" ]; then
  warn "Usage: $0 <slug> <type> [arg]"
  warn "  Types: phase <N>, content, loop"
  exit 1
fi

SLUG="$1"
TYPE="$2"
ARG="${3:-}"
CLIENT_DIR="${CLIENTS_DIR}/${SLUG}"
TODAY=$(date +%Y-%m-%d)
OUTBOX="${CLIENT_DIR}/outbox"

# Verify client workspace exists
if [ ! -d "$CLIENT_DIR" ]; then
  warn "Client workspace not found: $CLIENT_DIR"
  warn "Run: bash ~/.claude/skills/empire-builder/scripts/new-client.sh ${SLUG}"
  exit 1
fi

mkdir -p "$OUTBOX"

case "$TYPE" in

  phase)
    # Stage artifacts from a completed GSD phase
    PHASE_NUM="${ARG:-1}"
    PLANNING="${CLIENT_DIR}/.planning"

    step "Staging Phase ${PHASE_NUM} artifacts → outbox/"

    # Map phase number to output artifact
    case "$PHASE_NUM" in
      1)
        ARTIFACT="brand-bible.md"
        TEMPLATE="${TEMPLATES_DIR}/brand-bible.md"
        SUMMARY=$(find "${PLANNING}/phases" -name "*SUMMARY*" -path "*1-*" 2>/dev/null | head -1)
        ;;
      2)
        ARTIFACT="social-profiles.md"
        TEMPLATE="${TEMPLATES_DIR}/social-profiles.md"
        SUMMARY=$(find "${PLANNING}/phases" -name "*SUMMARY*" -path "*2-*" 2>/dev/null | head -1)
        ;;
      3)
        ARTIFACT="content-calendar.md"
        TEMPLATE="${TEMPLATES_DIR}/content-calendar.md"
        SUMMARY=$(find "${PLANNING}/phases" -name "*SUMMARY*" -path "*3-*" 2>/dev/null | head -1)
        # Also create content-pieces directory for this batch
        mkdir -p "${OUTBOX}/content-pieces/${TODAY}"
        ;;
      4)
        ARTIFACT="skool-setup.md"
        TEMPLATE="${TEMPLATES_DIR}/skool-setup.md"
        SUMMARY=$(find "${PLANNING}/phases" -name "*SUMMARY*" -path "*4-*" 2>/dev/null | head -1)
        ;;
      5)
        ARTIFACT="funnel.md"
        TEMPLATE="${TEMPLATES_DIR}/funnel.md"
        SUMMARY=$(find "${PLANNING}/phases" -name "*SUMMARY*" -path "*5-*" 2>/dev/null | head -1)
        ;;
      6)
        ARTIFACT="launch-checklist.md"
        TEMPLATE="${TEMPLATES_DIR}/roadmap.md"
        SUMMARY=$(find "${PLANNING}/phases" -name "*SUMMARY*" -path "*6-*" 2>/dev/null | head -1)
        ;;
      *)
        warn "Unknown phase: ${PHASE_NUM}"
        exit 1
        ;;
    esac

    TARGET="${OUTBOX}/${ARTIFACT}"

    if [ -n "${SUMMARY:-}" ] && [ -f "$SUMMARY" ]; then
      # GSD SUMMARY.md exists — copy it as the basis
      cp "$SUMMARY" "$TARGET"
      ok "Staged from GSD summary: ${ARTIFACT}"
    else
      # No GSD summary yet — copy template as placeholder
      if [ -f "$TEMPLATE" ]; then
        cp "$TEMPLATE" "$TARGET"
        ok "Staged template placeholder: ${ARTIFACT} (fill in with Phase ${PHASE_NUM} content)"
        warn "GSD SUMMARY.md not found — template staged as placeholder"
      else
        warn "No source found for phase ${PHASE_NUM}. Create ${ARTIFACT} manually in outbox/"
      fi
    fi

    bold ""
    bold "Phase ${PHASE_NUM} staged to: outbox/${ARTIFACT}"
    echo "  Show the founder this file and get approval before advancing."
    ;;

  content)
    # Stage this week's content pieces
    step "Staging content pieces → outbox/content-pieces/${TODAY}/"
    CONTENT_DIR="${OUTBOX}/content-pieces/${TODAY}"
    mkdir -p "$CONTENT_DIR"

    # Create the weekly content README if it doesn't exist
    if [ ! -f "${CONTENT_DIR}/README.md" ]; then
      cat > "${CONTENT_DIR}/README.md" <<EOF
# Content Batch — ${TODAY}

Generated by empire-builder growth loop for ${SLUG}.

## Files in this folder

| File | Platform | Type | Status |
|------|----------|------|--------|
| instagram-reel/ | Instagram | Reel | ready to post |
| tiktok/ | TikTok | Video | ready to post |
| youtube/ | YouTube | Outline | script content ready |
| x-thread/ | X/Threads | Thread | ready to post |

## How to publish

1. **Instagram Reel**: Record video using hook.txt for first 3 seconds, follow script.md, paste caption.md
2. **TikTok**: Same content as IG Reel, use TikTok caption
3. **YouTube**: Record using outline.md, use title.txt for upload title
4. **X Thread**: Copy-paste thread.md tweet by tweet

## Scheduled for
Post on: [fill in — ideally Mon/Wed/Fri pattern]
EOF
    fi

    mkdir -p \
      "${CONTENT_DIR}/instagram-reel" \
      "${CONTENT_DIR}/tiktok" \
      "${CONTENT_DIR}/youtube" \
      "${CONTENT_DIR}/x-thread"

    ok "Content piece directories created: outbox/content-pieces/${TODAY}/"
    bold ""
    bold "Content batch directory ready: outbox/content-pieces/${TODAY}/"
    echo "  The growth loop model will write content files into these directories."
    ;;

  loop)
    # Stage today's growth loop increment
    step "Staging loop increment → outbox/${TODAY}/"
    LOOP_DIR="${OUTBOX}/${TODAY}"
    mkdir -p "$LOOP_DIR"

    # Create a READY.md marker
    cat > "${LOOP_DIR}/READY.md" <<EOF
# Loop Increment — ${TODAY}

Staged by empire-builder growth loop for ${SLUG}.

## What's here
[Growth loop model fills this in after building the increment]

## To publish
[Growth loop model fills this in with specific publish instructions]

## Status
- [ ] Reviewed
- [ ] Published
- [ ] Logged in SESSION_STATE.md
EOF

    ok "Loop increment staged to: outbox/${TODAY}/"
    bold ""
    bold "Today's increment directory: outbox/${TODAY}/"
    echo "  The growth loop model writes the actual files here."
    ;;

  *)
    warn "Unknown type: ${TYPE}. Use: phase <N>, content, or loop"
    exit 1
    ;;
esac

# Update metrics.json timestamp
if [ -f "${CLIENT_DIR}/metrics.json" ]; then
  # Simple last_run update (macOS and Linux compatible)
  TMP=$(mktemp)
  sed "s/\"last_run\": null/\"last_run\": \"${TODAY}\"/" "${CLIENT_DIR}/metrics.json" > "$TMP" && \
  sed -i.bak "s/\"last_run\": \"[0-9-]*\"/\"last_run\": \"${TODAY}\"/" "${CLIENT_DIR}/metrics.json" 2>/dev/null || \
  mv "$TMP" "${CLIENT_DIR}/metrics.json"
  rm -f "$TMP" "${CLIENT_DIR}/metrics.json.bak" 2>/dev/null || true
fi
